before_install: chmod +x build.sh ./build-scripts/*.sh
script: ./build.sh
cache: .packages
deploy:
  provider: releases
  api-key: "520bd4384ea390e4fab29e8fdc43df0c56de3038"
  file_glob: true
  file: .dist/*
  skip_cleanup: true
  on:
    tags: true